all:
  children:
    ansible:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: ubuntu
    prod:
      hosts:
        worker01:
          ansible_host: 172.31.88.221
          hostname: AnsibleWorker01

        worker02:
          ansible_host: 172.31.93.217
          hostname: AnsibleWorker02

        worker03:
          ansible_user: centos
          ansible_password: 1twskp6
          ansible_host: 172.31.89.155
          hostname: AnsibleWorker03

