- name: run docker
  hosts: worker01
  
  vars_files:
  - files/secrets.yml
  roles:
    - docker_role

  tasks:
    - name: "Launch nginx container"
      docker_container:
        name: webapp
        image: nginx
        ports:
          - "8080:80"
